export const API_URL = 'https://jsonplaceholder.typicode.com/posts';

export const FETCH_DUMMY_DATA_REQUEST = 'FETCH_DUMMY_DATA_REQUEST';
export const FETCH_DUMMY_DATA_SUCCESS = 'FETCH_DUMMY_DATA_SUCCESS';
export const FETCH_DUMMY_DATA_FAILURE = 'FETCH_DUMMY_DATA_FAILURE';

export const LOADING_MODAL_OPEN = 'LOADING_MODAL_OPEN';
export const LOADING_MODAL_CLOSE = 'LOADING_MODAL_CLOSE';
